version: "3.3"
services:
    php-apache:
        ports:
            - 9001:80
        build: './build/php'
        volumes:
            - ./app:/var/www/html
    mysql_db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 9002:80
        environment:
            - PMA_ARBITRARY=1
volumes:
  app:
  dbData: